"""AUTO generate migration

Revision ID: 1ccf14f34c1a
Revises: 
Create Date: 2026-04-19 13:07:56.024754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



import sqlalchemy.sql.sqltypes 
from sqlmodel import Text

# revision identifiers, used by Alembic.
revision: str = '1ccf14f34c1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capsule_open_trigger'), table_name='capsules')
    op.drop_column('capsules', 'open_type')
    op.drop_column('capsules', 'open_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('open_at', sa.DATETIME(), nullable=False))
    op.add_column('capsules', sa.Column('open_type', sa.VARCHAR(length=8), nullable=False))
    op.create_index(op.f('ix_capsule_open_trigger'), 'capsules', ['open_at', 'status'], unique=False)
    # ### end Alembic commands ###
